type: object
description: >
    Component that loads auth configuration settings from a
    components::Secdist component if the latter was registered in
    components::ComponentList.
additionalProperties: false
properties: {}
