/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <cstdint>
#include <handlers/test/openapi.hpp>
#include <optional>
#include <string>
#include <userver/chaotic/openapi/parameters_read.hpp>
#include <userver/server/http/http_request.hpp>

namespace handlers::test::testme::post {

static constexpr USERVER_NAMESPACE::chaotic::openapi::Name knumber = "number";

static constexpr USERVER_NAMESPACE::chaotic::openapi::Name karray = "array";

/// Request parsed from HttpRequest for this operation.
struct Request final {
    std::string number;

    std::vector<std::string> array;

    int body;
};

Request
ParseRequest(const USERVER_NAMESPACE::server::http::HttpRequest& http_request, const USERVER_NAMESPACE::chaotic::openapi::To<Request>&);

}  // namespace handlers::test::testme::post
