"""Lists of C++ reserved identifiers."""

#: C++ Keywords (as of C++20/23).
CPP_KEYWORDS = {
    'alignas',
    'alignof',
    'and',
    'and_eq',
    'asm',
    'auto',
    'bitand',
    'bitor',
    'bool',
    'break',
    'case',
    'catch',
    'char',
    'char8_t',
    'char16_t',
    'char32_t',
    'class',
    'compl',
    'concept',
    'const',
    'consteval',
    'constexpr',
    'constinit',
    'const_cast',
    'continue',
    'co_await',
    'co_return',
    'co_yield',
    'decltype',
    'default',
    'delete',
    'do',
    'double',
    'dynamic_cast',
    'else',
    'enum',
    'explicit',
    'export',
    'extern',
    'false',
    'float',
    'for',
    'friend',
    'goto',
    'if',
    'inline',
    'int',
    'long',
    'mutable',
    'namespace',
    'new',
    'noexcept',
    'not',
    'not_eq',
    'nullptr',
    'operator',
    'or',
    'or_eq',
    'private',
    'protected',
    'public',
    'register',
    'reinterpret_cast',
    'requires',
    'return',
    'short',
    'signed',
    'sizeof',
    'static',
    'static_assert',
    'static_cast',
    'struct',
    'switch',
    'template',
    'this',
    'thread_local',
    'throw',
    'true',
    'try',
    'typedef',
    'typeid',
    'typename',
    'union',
    'unsigned',
    'using',
    'virtual',
    'void',
    'volatile',
    'wchar_t',
    'while',
    'xor',
    'xor_eq',
}

#: Alternative identifiers with special meaning (contextual keywords).
CPP_CONTEXTUAL_KEYWORDS = {
    'final',
    'override',
    'import',
    'module',
}

#: Identifiers reserved for possible future use.
CPP_EXTRA_RESERVED_IDENTIFIERS = {
    'reflexpr',  # Reflection TS
}

#: Popular macros from C++ standard library and userver.
CPP_POPULAR_MACROS = {
    'NULL',
    'assert',
    'LOG',
}

#: Combined set of all reserved identifiers.
CPP_RESERVED_IDENTIFIERS = CPP_KEYWORDS | CPP_CONTEXTUAL_KEYWORDS | CPP_EXTRA_RESERVED_IDENTIFIERS | CPP_POPULAR_MACROS
