/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <handlers/test/testme/post/handler.hpp>
#include <userver/chaotic/openapi/server/dependencies.hpp>
#include <userver/components/component_list.hpp>
#include <userver/components/container.hpp>

namespace handlers::test {

/// @brief Returns the component list with all generated handlers
/// and the chaotic-openapi dependency-injection container.
///
/// Add this list to your service's component list:
/// @code
/// component_list.AppendComponentList(handlers::test::ChaoticHandlersList());
/// @endcode
inline USERVER_NAMESPACE::components::ComponentList ChaoticHandlersList() {
    return USERVER_NAMESPACE::components::ComponentList()
        .Append<USERVER_NAMESPACE::components::Container<
            USERVER_NAMESPACE::chaotic::openapi::server::dependencies::Factories>>()

        .Append<handlers::test::testme::post::Handler>()

        ;
}

}  // namespace handlers::test
