#pragma once

#include <mongoc/mongoc.h>

#ifdef MONGOC_BULKWRITE_H
#define USERVER_FEATURE_MONGO_BULKWRITE
#endif

#if !defined(USERVER_MONGO_HAS_EXPERIMENTAL_DRIVER_API) || USERVER_MONGO_HAS_EXPERIMENTAL_DRIVER_API
#define USERVER_FEATURE_MONGO_EXPERIMENTAL
#endif
