/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <pg_queries/pg_client.hpp>

namespace pg_queries {

class ClusterPgClient : public PgClient {
public:
    ClusterPgClient(USERVER_NAMESPACE::storages::postgres::ClusterPtr);

    std::vector<CountUsersByStatusRow> CountUsersByStatus(HostType host_type) const override;

    std::vector<std::optional<QueriesUserProfile>> CreateProfileComposite(
        HostType host_type,
        const std::optional<std::string>& arg1,
        const std::optional<std::int32_t>& arg2,
        const std::optional<std::string>& arg3,
        const std::optional<bool>& arg4
    ) const override;

    std::vector<CreateUserRow> CreateUser(
        HostType host_type,
        const std::string& arg1,
        const std::string& arg2,
        const std::optional<QueriesUserStatus>& arg3
    ) const override;

    std::vector<DeleteUserRow> DeleteUser(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const override;

    void DeleteUserSimple(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const override;

    std::vector<GetActiveUsersRow> GetActiveUsers(HostType host_type) const override;

    std::vector<GetAllUsersRow> GetAllUsers(HostType host_type) const override;

    std::vector<std::optional<QueriesUserProfile>> GetUserAsComposite(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const override;

    std::vector<GetUserByIdRow> GetUserById(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const override;

    std::vector<GetUserProfileCompositeRow> GetUserProfileComposite(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const override;

    std::vector<GetUsersWithProfileRow> GetUsersWithProfile(HostType host_type) const override;

    void UpdateUserSimple(
        HostType host_type,
        const std::optional<std::int64_t>& arg1,
        const std::optional<QueriesUserStatus>& arg2
    ) const override;

    std::vector<UpdateUserStatusRow> UpdateUserStatus(
        HostType host_type,
        const std::optional<std::int64_t>& arg1,
        const std::optional<QueriesUserStatus>& arg2
    ) const override;

    ~ClusterPgClient() override = default;

private:
    USERVER_NAMESPACE::storages::postgres::ClusterPtr cluster_;
};

}  // namespace pg_queries
