/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <pg_queries/pg_models.hpp>
#include <userver/storages/postgres/cluster.hpp>
#include <userver/storages/postgres/io/array_types.hpp>
#include <userver/storages/postgres/io/chrono.hpp>
#include <userver/storages/postgres/io/enum_types.hpp>
#include <userver/storages/postgres/io/integral_types.hpp>
#include <userver/storages/postgres/io/io_fwd.hpp>
#include <userver/storages/postgres/io/optional.hpp>
#include <userver/storages/postgres/io/row_types.hpp>
#include <userver/storages/postgres/io/string_types.hpp>
#include <userver/storages/postgres/postgres_fwd.hpp>

namespace pg_queries {

struct CountUsersByStatusRow {
    std::optional<QueriesUserStatus> status;
    std::optional<std::int64_t> user_count;
};

struct CreateUserRow {
    std::optional<std::int64_t> id;
    std::optional<std::string> username;
    std::optional<std::string> email;
    std::optional<QueriesUserStatus> status;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> created_at;
};

struct DeleteUserRow {
    std::optional<std::int64_t> id;
    std::optional<std::string> username;
};

struct GetActiveUsersRow {
    std::optional<std::int64_t> id;
    std::optional<std::string> username;
    std::optional<std::string> email;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> created_at;
};

struct GetAllUsersRow {
    std::optional<std::int64_t> id;
    std::optional<std::string> username;
    std::optional<std::string> email;
    std::optional<QueriesUserStatus> status;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> created_at;
};

struct GetUserByIdRow {
    std::optional<std::int64_t> id;
    std::optional<std::string> username;
    std::optional<std::string> email;
    std::optional<QueriesUserStatus> status;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> created_at;
};

struct GetUserProfileCompositeRow {
    std::optional<std::string> display_name;
    std::optional<std::int32_t> age;
    std::optional<std::string> country;
    std::optional<bool> is_verified;
};

struct GetUsersWithProfileRow {
    std::optional<std::int64_t> id;
    std::optional<std::string> username;
    std::optional<std::string> email;
    std::optional<QueriesUserProfile> profile;
    std::optional<std::vector<std::string>> tags;
};

struct UpdateUserStatusRow {
    std::optional<std::int64_t> id;
    std::optional<std::string> username;
    std::optional<QueriesUserStatus> status;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> updated_at;
};

class PgClient {
public:
    using HostType = USERVER_NAMESPACE::storages::postgres::ClusterHostTypeFlags;

    virtual std::vector<CountUsersByStatusRow> CountUsersByStatus(HostType host_type) const = 0;

    virtual std::vector<std::optional<QueriesUserProfile>> CreateProfileComposite(
        HostType host_type,
        const std::optional<std::string>& arg1,
        const std::optional<std::int32_t>& arg2,
        const std::optional<std::string>& arg3,
        const std::optional<bool>& arg4
    ) const = 0;

    virtual std::vector<CreateUserRow> CreateUser(
        HostType host_type,
        const std::string& arg1,
        const std::string& arg2,
        const std::optional<QueriesUserStatus>& arg3
    ) const = 0;

    virtual std::vector<DeleteUserRow> DeleteUser(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const = 0;

    virtual void DeleteUserSimple(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const = 0;

    virtual std::vector<GetActiveUsersRow> GetActiveUsers(HostType host_type) const = 0;

    virtual std::vector<GetAllUsersRow> GetAllUsers(HostType host_type) const = 0;

    virtual std::vector<std::optional<QueriesUserProfile>> GetUserAsComposite(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const = 0;

    virtual std::vector<GetUserByIdRow> GetUserById(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const = 0;

    virtual std::vector<GetUserProfileCompositeRow> GetUserProfileComposite(
        HostType host_type,
        const std::optional<std::int64_t>& arg1
    ) const = 0;

    virtual std::vector<GetUsersWithProfileRow> GetUsersWithProfile(HostType host_type) const = 0;

    virtual void UpdateUserSimple(
        HostType host_type,
        const std::optional<std::int64_t>& arg1,
        const std::optional<QueriesUserStatus>& arg2
    ) const = 0;

    virtual std::vector<UpdateUserStatusRow> UpdateUserStatus(
        HostType host_type,
        const std::optional<std::int64_t>& arg1,
        const std::optional<QueriesUserStatus>& arg2
    ) const = 0;

    virtual ~PgClient() = default;
};

}  // namespace pg_queries
