/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <userver/storages/postgres/io/array_types.hpp>
#include <userver/storages/postgres/io/chrono.hpp>
#include <userver/storages/postgres/io/enum_types.hpp>
#include <userver/storages/postgres/io/integral_types.hpp>
#include <userver/storages/postgres/io/io_fwd.hpp>
#include <userver/storages/postgres/io/optional.hpp>
#include <userver/storages/postgres/io/string_types.hpp>

namespace pg_queries {

enum class QueriesUserStatus {
    kActive,   // active
    kBlocked,  // blocked
    kDeleted,  // deleted
};

struct QueriesUserProfile {
    std::optional<std::string> display_name;
    std::optional<std::int32_t> age;
    std::optional<std::string> country;
    std::optional<bool> is_verified;
};

struct QueriesUsersV0 {
    std::int64_t id{};
    std::string username;
    std::string email;
    std::optional<QueriesUserStatus> status;
    std::optional<QueriesUserProfile> profile;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> created_at;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> updated_at;
    std::optional<std::vector<std::string>> tags;
};
using QueriesUsers = QueriesUsersV0;

}  // namespace pg_queries

USERVER_NAMESPACE_BEGIN

namespace storages::postgres::io {

template <>
struct CppToUserPg<pg_queries::QueriesUserStatus> : EnumMappingBase<pg_queries::QueriesUserStatus> {
    static constexpr DBTypeName postgres_name = "queries.user_status";
    static constexpr Enumerator enumerators[] = {
        {EnumType::kActive, "active"},
        {EnumType::kBlocked, "blocked"},
        {EnumType::kDeleted, "deleted"},
    };
};

template <>
struct CppToUserPg<pg_queries::QueriesUserProfile> {
    static constexpr DBTypeName postgres_name = "queries.user_profile";
};

template <>
struct CppToUserPg<pg_queries::QueriesUsersV0> {
    static constexpr DBTypeName postgres_name = "queries.users_v0";
};

}  // namespace storages::postgres::io

USERVER_NAMESPACE_END
