linters:
    # silence linters since testsuite package is not available for them
    disable-plugins:
        pylint:
          - import-error
          - import-only-modules
          - invalid-name
          - no-name-in-module
          - redefined-outer-name
        flake8:
          - I202
