# yaml
server-name: test-core-metrics 1.0
service-name: test_core_metrics
logger-level: info

config-server-url: http://localhost:8083/
server-port: 8185
monitor-server-port: 8186

testsuite-enabled: false

userver-dumps-root: /var/cache/test_core_metrics/userver-dumps/
access-log-path: /var/log/test_core_metrics/access.log
access-tskv-log-path: /var/log/test_core_metrics/access_tskv.log
default-log-path: /var/log/test_core_metrics/server.log
secdist-path: /etc/test_core_metrics/secure_data.json

config-cache: /var/cache/test_core_metrics/config_cache.json
config-fallback: /etc/test_core_metrics/dynamic_config_fallback.json
