/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <boost/uuid/uuid.hpp>
#include <userver/storages/postgres/io/chrono.hpp>
#include <userver/storages/postgres/io/decimal64.hpp>
#include <userver/storages/postgres/io/enum_types.hpp>
#include <userver/storages/postgres/io/floating_point_types.hpp>
#include <userver/storages/postgres/io/integral_types.hpp>
#include <userver/storages/postgres/io/json_types.hpp>
#include <userver/storages/postgres/io/optional.hpp>
#include <userver/storages/postgres/io/range_types.hpp>
#include <userver/storages/postgres/io/string_types.hpp>
#include <userver/storages/postgres/io/uuid.hpp>

namespace pg_models {

enum class TestStatusType {
    kActive,    // active
    kInactive,  // inactive
    kPending,   // pending
};

struct TestUserData {
    std::optional<std::int16_t> small_num;
    std::optional<std::int32_t> regular_num;
    std::optional<std::int64_t> big_num;
    std::optional<std::string> name;
    std::optional<std::string> code;
    std::optional<std::string> single_char;
    std::optional<bool> is_enabled;
    std::optional<float> rate;
    std::optional<double> precise_rate;
    std::optional<USERVER_NAMESPACE::decimal64::Decimal<2>> balance;
    std::optional<USERVER_NAMESPACE::decimal64::Decimal<4>> score;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> created_at;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointWithoutTz> updated_at;
    std::optional<USERVER_NAMESPACE::storages::postgres::Date> birth_date;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimeOfDay> work_time;
    std::optional<std::chrono::microseconds> duration;
    std::optional<boost::uuids::uuid> user_uuid;
    std::optional<USERVER_NAMESPACE::formats::json::Value> metadata;
    std::optional<USERVER_NAMESPACE::formats::json::Value> settings;
    std::optional<std::string> avatar;
    std::optional<USERVER_NAMESPACE::storages::postgres::IntegerRange> age_range;
    std::optional<USERVER_NAMESPACE::storages::postgres::BigintRange> id_range;
    std::optional<TestStatusType> status;
};

}  // namespace pg_models

USERVER_NAMESPACE_BEGIN

namespace storages::postgres::io {

template <>
struct CppToUserPg<pg_models::TestStatusType> : EnumMappingBase<pg_models::TestStatusType> {
    static constexpr DBTypeName postgres_name = "test.status_type";
    static constexpr Enumerator enumerators[] = {
        {EnumType::kActive, "active"},
        {EnumType::kInactive, "inactive"},
        {EnumType::kPending, "pending"},
    };
};

template <>
struct CppToUserPg<pg_models::TestUserData> {
    static constexpr DBTypeName postgres_name = "test.user_data";
};

}  // namespace storages::postgres::io

USERVER_NAMESPACE_END
