from userver_gdb_tests.test_gen_gdb_printers_tests import test_utask_embedded_script_function_prefixes
from userver_gdb_tests.test_printers import test_gdb_printers

__all__ = ['test_gdb_printers', 'test_utask_embedded_script_function_prefixes']
