-- Migration is auto-generated by sqldto

CREATE TYPE queries.users_v0 AS (
    id BIGINT,
    username CHARACTER VARYING(50),
    email TEXT,
    status QUERIES.USER_STATUS,
    profile QUERIES.USER_PROFILE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    tags TEXT[]
);
