# AUTOGENERATED, DON'T CHANGE THIS FILE!

if (NOT CurlYandex_FIND_VERSION OR CurlYandex_FIND_VERSION VERSION_LESS 7.68.0)
    set(CurlYandex_FIND_VERSION 7.68.0)
endif()

if (NOT USERVER_CHECK_PACKAGE_VERSIONS)
  unset(CurlYandex_FIND_VERSION)
endif()

if (TARGET CurlYandex)
  if (NOT CurlYandex_FIND_VERSION)
      set(CurlYandex_FOUND ON)
      return()
  endif()

  if (CurlYandex_VERSION)
      if (CurlYandex_FIND_VERSION VERSION_LESS_EQUAL CurlYandex_VERSION)
          set(CurlYandex_FOUND ON)
          return()
      else()
          message(FATAL_ERROR
              "Already using version ${CurlYandex_VERSION} "
              "of CurlYandex when version ${CurlYandex_FIND_VERSION} "
              "was requested."
          )
      endif()
  endif()
endif()

set(FULL_ERROR_MESSAGE "Could not find `CurlYandex` package.\n\tDebian: sudo apt update && sudo apt install libyandex-taxi-curl4-openssl-dev\n\tMacOS: brew install curl")


include(FindPackageHandleStandardArgs)





if (CurlYandex_VERSION)
  set(CurlYandex_VERSION ${CurlYandex_VERSION})
endif()

if (CurlYandex_FIND_VERSION AND NOT CurlYandex_VERSION)
  include(DetectVersion)

  if (UNIX AND NOT APPLE)
    deb_version(CurlYandex_VERSION libyandex-taxi-curl4-openssl-dev)
  endif()
  if (APPLE)
    brew_version(CurlYandex_VERSION curl)
  endif()
endif()

find_package(CurlYandex 7.68.0
 )
set(CurlYandex_FOUND ${CurlYandex_FOUND})
 

if (NOT CurlYandex_FOUND)
  if (CurlYandex_FIND_REQUIRED)
      message(FATAL_ERROR "${FULL_ERROR_MESSAGE}. Required version is at least ${CurlYandex_FIND_VERSION}")
  endif()

  return()
endif()

if (CurlYandex_FIND_VERSION)
  if (CurlYandex_VERSION VERSION_LESS CurlYandex_FIND_VERSION)
      message(STATUS
          "Version of CurlYandex is '${CurlYandex_VERSION}'. "
          "Required version is at least '${CurlYandex_FIND_VERSION}'. "
          "Ignoring found CurlYandex."
          "Note: Set -DUSERVER_CHECK_PACKAGE_VERSIONS=0 to skip package version checks if the package is fine."
      )
      set(CurlYandex_FOUND OFF)
      return()
  endif()
endif()

 
if (NOT TARGET CurlYandex)
  add_library(CurlYandex INTERFACE IMPORTED GLOBAL)

  target_include_directories(CurlYandex INTERFACE ${CurlYandex_INCLUDE_DIRS})
  target_link_libraries(CurlYandex INTERFACE ${CurlYandex_LIBRARIES})
  
  # Target CurlYandex is created
endif()

if (CurlYandex_VERSION)
  set(CurlYandex_VERSION "${CurlYandex_VERSION}" CACHE STRING "Version of the CurlYandex")
endif()
