#!/bin/bash

###
### Provide additional CMake configuration options or override the
### existing ones via BUILD_OPTIONS and PACKAGE_OPTIONS variables.
###

# Exit on any error and treat unset variables as errors, print all commands
set -euox pipefail



BUILD_OPTIONS="
    -DUSERVER_BUILD_ALL_COMPONENTS=1 \
    -DUSERVER_FEATURE_YDB=0 \
    -DUSERVER_BUILD_SAMPLES=ON \
    -DUSERVER_FEATURE_GRPC_CHANNELZ=0 \
    -DUSERVER_FEATURE_MONGODB=ON \
    -DUSERVER_FEATURE_MYSQL=OFF \
    -DUSERVER_FEATURE_POSTGRESQL=OFF \
    -DUSERVER_FEATURE_SCYLLADB=ON \
    -DUSERVER_FEATURE_STACKTRACE=0 \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DUSERVER_FEATURE_EASY=OFF \
    -DUSERVER_FEATURE_GRPC=OFF \
    -DUSERVER_FEATURE_OTLP=OFF \
    -DUSERVER_FEATURE_GRPC_REFLECTION=OFF \
    ${BUILD_OPTIONS:-""} \
"
CONFIGURE_RETRIES="${CONFIGURE_RETRIES:-5}"

BUILD_OPTIONS="$BUILD_OPTIONS" CONFIGURE_RETRIES="$CONFIGURE_RETRIES" "$(dirname "$(realpath "$0")")/local_build_and_install.sh"