#!/usr/bin/env python3
import pathlib
import click

import changelog_tool.config as cfg
import changelog_tool.collect.command as collect_cmd

@click.group()
@click.option('--config', default='changelog.yaml')
@click.pass_context
def cli(ctx: click.Context, config: str):
    ctx.ensure_object(dict)
    ctx.obj["CONFIG"] = cfg.parse_config(pathlib.Path(config))

@cli.command()
@click.option('--from-sha')
@click.option('--to-sha')
@click.option('--repo-path', type=pathlib.Path)
@click.pass_context
def collect(ctx: click.Context, from_sha: str | None, to_sha: str | None, repo_path: pathlib.Path | None):
    # Get the config and override with CLI options if provided
    config = ctx.obj["CONFIG"].collect
    if from_sha:
        config.from_sha = from_sha
    if to_sha:
        config.to_sha = to_sha
    if repo_path:
        config.repo_path = repo_path
    
    collect_cmd.collect(config)

if __name__ == '__main__':
    cli()