#!/usr/bin/env python3
import pathlib
import click

import changelog_tool.config as cfg
import changelog_tool.collect.command as collect_cmd

@click.group()
@click.option('--config', default='changelog.yaml')
@click.option('--output-dir', type=pathlib.Path, default=None)
@click.pass_context
def cli(ctx: click.Context, config: str, output_dir: pathlib.Path | None):
    ctx.ensure_object(dict)
    parsed_config = cfg.parse_config(pathlib.Path(config))
    if output_dir:
        parsed_config.collect.output_dir = output_dir
    ctx.obj["CONFIG"] = parsed_config

@cli.command()
@click.option('--from-sha')
@click.option('--to-sha')
@click.option('--repo-path', type=pathlib.Path)
@click.pass_context
def collect(ctx: click.Context, from_sha: str | None, to_sha: str | None, repo_path: pathlib.Path | None):
    # Get the config and override with CLI options if provided
    config = ctx.obj["CONFIG"]
    if from_sha:
        config.collect.from_sha = from_sha
    if to_sha:
        config.collect.to_sha = to_sha
    if repo_path:
        config.collect.repo_path = repo_path
    
    collect_cmd.collect(config)

if __name__ == '__main__':
    cli()