/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <userver/storages/postgres/io/array_types.hpp>
#include <userver/storages/postgres/io/chrono.hpp>
#include <userver/storages/postgres/io/enum_types.hpp>
#include <userver/storages/postgres/io/integral_types.hpp>
#include <userver/storages/postgres/io/io_fwd.hpp>
#include <userver/storages/postgres/io/optional.hpp>
#include <userver/storages/postgres/io/string_types.hpp>

namespace pg_arrays {

enum class NestedCategory {
    kWork,      // work
    kPersonal,  // personal
    kOther,     // other
};

enum class NestedPriority {
    kLow,   // low
    kHigh,  // high
};

struct NestedAddress {
    std::optional<std::string> street;
    std::optional<std::string> city;
    std::optional<std::string> postal_code;
};

struct NestedContact {
    std::optional<std::string> phone;
    std::optional<std::string> email;
    std::optional<bool> is_primary;
};

struct NestedPerson {
    std::optional<std::string> name;
    std::optional<std::int32_t> age;
    std::optional<NestedContact> contacts;
    std::optional<NestedAddress> home_address;
    std::optional<NestedAddress> work_address;
    std::optional<NestedPriority> priority;
};

struct NestedOrganization {
    std::optional<std::int64_t> org_id;
    std::optional<std::string> org_name;
    std::optional<USERVER_NAMESPACE::storages::postgres::Date> founded;
    std::optional<NestedAddress> headquarters;
    std::optional<std::vector<std::string>> phone_numbers;
    std::optional<std::vector<std::int32_t>> employee_counts;
    std::optional<std::vector<NestedAddress>> locations;
    std::optional<std::vector<NestedContact>> key_contacts;
    std::optional<std::vector<NestedCategory>> categories;
    std::optional<NestedPerson> ceo;
    std::optional<std::vector<NestedPerson>> employees;
};

}  // namespace pg_arrays

USERVER_NAMESPACE_BEGIN

namespace storages::postgres::io {

template <>
struct CppToUserPg<pg_arrays::NestedCategory> : EnumMappingBase<pg_arrays::NestedCategory> {
    static constexpr DBTypeName postgres_name = "nested.category";
    static constexpr Enumerator enumerators[] = {
        {EnumType::kWork, "work"},
        {EnumType::kPersonal, "personal"},
        {EnumType::kOther, "other"},
    };
};

template <>
struct CppToUserPg<pg_arrays::NestedPriority> : EnumMappingBase<pg_arrays::NestedPriority> {
    static constexpr DBTypeName postgres_name = "nested.priority";
    static constexpr Enumerator enumerators[] = {
        {EnumType::kLow, "low"},
        {EnumType::kHigh, "high"},
    };
};

template <>
struct CppToUserPg<pg_arrays::NestedAddress> {
    static constexpr DBTypeName postgres_name = "nested.address";
};

template <>
struct CppToUserPg<pg_arrays::NestedContact> {
    static constexpr DBTypeName postgres_name = "nested.contact";
};

template <>
struct CppToUserPg<pg_arrays::NestedPerson> {
    static constexpr DBTypeName postgres_name = "nested.person";
};

template <>
struct CppToUserPg<pg_arrays::NestedOrganization> {
    static constexpr DBTypeName postgres_name = "nested.organization";
};

}  // namespace storages::postgres::io

USERVER_NAMESPACE_END
