-- Migration is auto-generated by sqldto

CREATE TYPE tables.posts_v0 AS (
    id BIGINT,
    author_id BIGINT,
    title CHARACTER VARYING(200),
    content TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    view_count INTEGER,
    is_published BOOLEAN
);

CREATE TYPE tables.users_v0 AS (
    id BIGINT,
    username CHARACTER VARYING(50),
    email TEXT,
    password_hash CHARACTER(64),
    age SMALLINT,
    balance NUMERIC(10,2),
    rating REAL,
    created_at TIMESTAMP WITH TIME ZONE,
    last_login TIMESTAMP WITHOUT TIME ZONE,
    birth_date DATE,
    external_id UUID,
    is_active BOOLEAN,
    is_deleted BOOLEAN,
    preferences JSONB,
    metadata JSON,
    role TABLES.USER_ROLE,
    profile TABLES.PROFILE_DATA,
    tags TEXT[],
    favorite_numbers INTEGER[],
    avatar BYTEA,
    session_duration INTERVAL,
    valid_age_range INT4RANGE
);
