/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <dynamic_config/variables/BOOL_FLAG.types.hpp>

#include <userver/chaotic/dynamic_config_variable_bundle.hpp>
#include <userver/dynamic_config/snapshot.hpp>

namespace dynamic_config {

namespace bool_flag {

using VariableType = VariableTypeRaw;
using BoolFlag = VariableTypeRaw;

}  // namespace bool_flag

extern const USERVER_NAMESPACE::dynamic_config::Key<
    bool
> BOOL_FLAG;

}  // namespace dynamic_config
