/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <dynamic_config/variables/CONNECTION_POOL_SETTINGS.types.hpp>

#include <userver/chaotic/dynamic_config_variable_bundle.hpp>
#include <userver/dynamic_config/snapshot.hpp>

namespace dynamic_config {

namespace connection_pool_settings {

using VariableType = USERVER_NAMESPACE::utils::DefaultDict<::dynamic_config::connection_pool_settings::PoolSettings>;
using ConnectionPoolSettings = USERVER_NAMESPACE::utils::DefaultDict<::dynamic_config::connection_pool_settings::PoolSettings>;

}  // namespace connection_pool_settings

extern const USERVER_NAMESPACE::dynamic_config::Key<
    USERVER_NAMESPACE::utils::DefaultDict<::dynamic_config::connection_pool_settings::PoolSettings>
> CONNECTION_POOL_SETTINGS;

}  // namespace dynamic_config
