/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <dynamic_config/variables/FEATURE_FLAGS.types.hpp>

#include <userver/chaotic/dynamic_config_variable_bundle.hpp>
#include <userver/dynamic_config/snapshot.hpp>

namespace dynamic_config {

namespace feature_flags {

using VariableType = VariableTypeRaw;
using FeatureFlags = VariableTypeRaw;

}  // namespace feature_flags

extern const USERVER_NAMESPACE::dynamic_config::Key<
    ::dynamic_config::feature_flags::VariableTypeRaw
> FEATURE_FLAGS;

}  // namespace dynamic_config
