components_manager:
    components:
        handler-metrics-clickhouse:
            path: /metrics/clickhouse
            task_processor: main-task-processor
            method: GET,DELETE,POST

        clickhouse-database:
            secdist_alias: clickhouse-database-alias
            initial_pool_size: 5
            max_pool_size: 10
            queue_timeout: 1s
            use_secure_connection: false
            compression: lz4

        secdist: {}
        default-secdist-provider:
            config: /etc/clickhouse_basic_chaos/secure_data.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        testsuite-support:

        http-client:
            fs-task-processor: main-task-processor

        tests-control:
            method: POST
            path: /tests/{action}
            skip-unregistered-testpoints: true
            task_processor: main-task-processor
            testpoint-timeout: 10s
            testpoint-url: $mockserver/testpoint
            throttling_enabled: false

        server:
            listener:
                port: 8187
                task_processor: main-task-processor
            listener-monitor:
                port: $monitor-server-port
                port#fallback: 8086
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        handler-server-monitor:
            path: /service/monitor
            method: GET
            task_processor: main-task-processor

        tracer:
            service-name: clickhouse-basic-chaos

        dynamic-config:
            fs-cache-path: ''
        dynamic-config-fallbacks:
            fallback-path: /etc/clickhouse_basic_chaos/dynamic_config_fallback.json
        dns-client:
            fs-task-processor: fs-task-processor
    coro_pool:
        initial_size: 500
        max_size: 1000

    task_processors:

        main-task-processor:
            worker_threads: 4
            thread_name: main-worker

        fs-task-processor:
            thread_name: fs-worker
            worker_threads: 4

    default_task_processor: main-task-processor
