/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <userver/chaotic/openapi/client/command_control.hpp>

#include "requests.hpp"
#include "responses.hpp"

namespace clients::test {

class Client {
public:
    /// POST /testme
    /// A testing method to call
    /// @throw testme::post::Exception

    virtual testme::post::Response TestmePost(
        const testme::post::Request& request,
        const USERVER_NAMESPACE::chaotic::openapi::client::CommandControl& command_control = {}
    ) = 0;

    virtual ~Client();
};

}  // namespace clients::test
