/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <userver/chaotic/array.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/sax_parser.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>

#include "clients/test/openapi.hpp"

namespace clients {
namespace test {
namespace testme {
namespace post {}  // namespace post
}  // namespace testme
}  // namespace test
}  // namespace clients
