/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <string>
#include <userver/chaotic/io/std/vector.hpp>
#include <userver/chaotic/type_bundle_hpp.hpp>

#include "clients/test/openapi_fwd.hpp"

namespace clients {
namespace test {
namespace testme {
namespace post {

using Parameter1 = std::vector<std::string>;

}  // namespace post
}  // namespace testme
}  // namespace test
}  // namespace clients
