/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <userver/chaotic/openapi/client/command_control.hpp>

namespace clients::test {

inline const USERVER_NAMESPACE::dynamic_config::Key<USERVER_NAMESPACE::chaotic::openapi::client::CommandControlDict>
    kQosConfig{"", USERVER_NAMESPACE::dynamic_config::DefaultAsJsonString{"{}"}};

}  // namespace clients::test
