/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <clients/test/openapi.hpp>
#include <cstdint>
#include <string>
#include <userver/clients/http/request.hpp>

namespace clients::test {

namespace testme::post {
using Body = int;

struct Request {
    std::string number;

    std::vector<std::string> array;

    Body body;
};

void SerializeRequest(
    const Request& request,
    const std::string& base_url,
    USERVER_NAMESPACE::clients::http::Request& http_request
);
}  // namespace testme::post

}  // namespace clients::test
