/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <variant>

#include <clients/test/exceptions.hpp>
#include <userver/chaotic/openapi/client/exceptions.hpp>
#include <optional>

#include <clients/test/openapi.hpp>

USERVER_NAMESPACE_BEGIN
namespace clients::http {
class Response;
}
USERVER_NAMESPACE_END

namespace clients::test {

namespace testme::post {

  struct Response200{
        std::optional<std::string>X_Header;

  };

  using Response =Response200;

Response ParseResponse(USERVER_NAMESPACE::clients::http::Response& response);
}

}
