/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <clients/test/exceptions.hpp>
#include <clients/test/openapi.hpp>
#include <userver/chaotic/openapi/client/exceptions.hpp>
#include <variant>

USERVER_NAMESPACE_BEGIN
namespace clients::http {
class Response;
}
USERVER_NAMESPACE_END

namespace clients::test {

namespace testme::post {

struct Response200 {};

using Response = Response200;

Response ParseResponse(USERVER_NAMESPACE::clients::http::Response& response);
}  // namespace testme::post

}  // namespace clients::test
