components_manager:
    components:
        handler-chaos:
            path: /chaos
            task_processor: main-task-processor
            method: GET,POST,DELETE

        key-value-db:
            initial_pool_size: 1
            max_pool_size: 1

        secdist:
            config: /etc/mysql_service/secure_data.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        server:
            listener:
                port: 8093
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        dns-client:
            fs-task-processor: fs-task-processor

    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 4

    default_task_processor: main-task-processor
