/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <pg_queries/pg_cluster.hpp>
#include <pg_queries/sql_queries.hpp>

namespace pg_queries {

ClusterPgClient::ClusterPgClient(USERVER_NAMESPACE::storages::postgres::ClusterPtr cluster) : cluster_(cluster) {}

std::vector<CountUsersByStatusRow> ClusterPgClient::CountUsersByStatus(HostType host_type) const {
    return cluster_->Execute(host_type, sql::kCountUsersByStatus)
        .AsContainer<std::vector<CountUsersByStatusRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

std::vector<std::optional<QueriesUserProfile>> ClusterPgClient::CreateProfileComposite(
    HostType host_type,
    const std::optional<std::string>& arg1,
    const std::optional<std::int32_t>& arg2,
    const std::optional<std::string>& arg3,
    const std::optional<bool>& arg4
) const {
    return cluster_->Execute(host_type, sql::kCreateProfileComposite, arg1, arg2, arg3, arg4)
        .AsContainer<std::vector<std::optional<QueriesUserProfile>>>();
}

std::vector<CreateUserRow> ClusterPgClient::CreateUser(
    HostType host_type,
    const std::string& arg1,
    const std::string& arg2,
    const std::optional<QueriesUserStatus>& arg3
) const {
    return cluster_->Execute(host_type, sql::kCreateUser, arg1, arg2, arg3)
        .AsContainer<std::vector<CreateUserRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

std::vector<DeleteUserRow> ClusterPgClient::DeleteUser(
    HostType host_type,
    const std::optional<std::int64_t>& arg1
) const {
    return cluster_->Execute(host_type, sql::kDeleteUser, arg1)
        .AsContainer<std::vector<DeleteUserRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

void ClusterPgClient::DeleteUserSimple(
    HostType host_type,
    const std::optional<std::int64_t>& arg1
) const {
    cluster_->Execute(host_type, sql::kDeleteUserSimple, arg1);
}

std::vector<GetActiveUsersRow> ClusterPgClient::GetActiveUsers(HostType host_type) const {
    return cluster_->Execute(host_type, sql::kGetActiveUsers)
        .AsContainer<std::vector<GetActiveUsersRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

std::vector<GetAllUsersRow> ClusterPgClient::GetAllUsers(HostType host_type) const {
    return cluster_->Execute(host_type, sql::kGetAllUsers)
        .AsContainer<std::vector<GetAllUsersRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

std::vector<std::optional<QueriesUserProfile>> ClusterPgClient::GetUserAsComposite(
    HostType host_type,
    const std::optional<std::int64_t>& arg1
) const {
    return cluster_->Execute(host_type, sql::kGetUserAsComposite, arg1)
        .AsContainer<std::vector<std::optional<QueriesUserProfile>>>();
}

std::vector<GetUserByIdRow> ClusterPgClient::GetUserById(
    HostType host_type,
    const std::optional<std::int64_t>& arg1
) const {
    return cluster_->Execute(host_type, sql::kGetUserById, arg1)
        .AsContainer<std::vector<GetUserByIdRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

std::vector<GetUserProfileCompositeRow> ClusterPgClient::GetUserProfileComposite(
    HostType host_type,
    const std::optional<std::int64_t>& arg1
) const {
    return cluster_->Execute(host_type, sql::kGetUserProfileComposite, arg1)
        .AsContainer<std::vector<GetUserProfileCompositeRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

std::vector<GetUsersWithProfileRow> ClusterPgClient::GetUsersWithProfile(HostType host_type) const {
    return cluster_->Execute(host_type, sql::kGetUsersWithProfile)
        .AsContainer<std::vector<GetUsersWithProfileRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

void ClusterPgClient::UpdateUserSimple(
    HostType host_type,
    const std::optional<std::int64_t>& arg1,
    const std::optional<QueriesUserStatus>& arg2
) const {
    cluster_->Execute(host_type, sql::kUpdateUserSimple, arg1, arg2);
}

std::vector<UpdateUserStatusRow> ClusterPgClient::UpdateUserStatus(
    HostType host_type,
    const std::optional<std::int64_t>& arg1,
    const std::optional<QueriesUserStatus>& arg2
) const {
    return cluster_->Execute(host_type, sql::kUpdateUserStatus, arg1, arg2)
        .AsContainer<std::vector<UpdateUserStatusRow>>(USERVER_NAMESPACE::storages::postgres::kRowTag);
}

}  // namespace pg_queries
