/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#pragma once

#include <boost/uuid/uuid.hpp>
#include <userver/storages/postgres/io/array_types.hpp>
#include <userver/storages/postgres/io/chrono.hpp>
#include <userver/storages/postgres/io/decimal64.hpp>
#include <userver/storages/postgres/io/enum_types.hpp>
#include <userver/storages/postgres/io/floating_point_types.hpp>
#include <userver/storages/postgres/io/integral_types.hpp>
#include <userver/storages/postgres/io/io_fwd.hpp>
#include <userver/storages/postgres/io/json_types.hpp>
#include <userver/storages/postgres/io/optional.hpp>
#include <userver/storages/postgres/io/range_types.hpp>
#include <userver/storages/postgres/io/string_types.hpp>
#include <userver/storages/postgres/io/uuid.hpp>

namespace pg_tables {

enum class TablesUserRole {
    kAdmin,  // admin
    kUser,   // user
    kGuest,  // guest
};

struct TablesProfileData {
    std::optional<std::string> first_name;
    std::optional<std::string> last_name;
    std::optional<std::int32_t> birth_year;
    std::optional<bool> is_verified;
};

struct TablesPostsV0 {
    std::int64_t id{};
    std::optional<std::int64_t> author_id;
    std::string title;
    std::optional<std::string> content;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> published_at;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> updated_at;
    std::optional<std::int32_t> view_count;
    std::optional<bool> is_published;
};

struct TablesUsersV0 {
    std::int64_t id{};
    std::string username;
    std::string email;
    std::optional<std::string> password_hash;
    std::optional<std::int16_t> age;
    std::optional<USERVER_NAMESPACE::decimal64::Decimal<2>> balance;
    std::optional<float> rating;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointTz> created_at;
    std::optional<USERVER_NAMESPACE::storages::postgres::TimePointWithoutTz> last_login;
    std::optional<USERVER_NAMESPACE::storages::postgres::Date> birth_date;
    std::optional<boost::uuids::uuid> external_id;
    std::optional<bool> is_active;
    std::optional<bool> is_deleted;
    std::optional<USERVER_NAMESPACE::formats::json::Value> preferences;
    std::optional<USERVER_NAMESPACE::formats::json::Value> metadata;
    std::optional<TablesUserRole> role;
    std::optional<TablesProfileData> profile;
    std::optional<std::vector<std::string>> tags;
    std::optional<std::vector<std::int32_t>> favorite_numbers;
    std::optional<std::string> avatar;
    std::optional<std::chrono::microseconds> session_duration;
    std::optional<USERVER_NAMESPACE::storages::postgres::IntegerRange> valid_age_range;
};
using TablesPosts = TablesPostsV0;
using TablesUsers = TablesUsersV0;

}  // namespace pg_tables

USERVER_NAMESPACE_BEGIN

namespace storages::postgres::io {

template <>
struct CppToUserPg<pg_tables::TablesUserRole> : EnumMappingBase<pg_tables::TablesUserRole> {
    static constexpr DBTypeName postgres_name = "tables.user_role";
    static constexpr Enumerator enumerators[] = {
        {EnumType::kAdmin, "admin"},
        {EnumType::kUser, "user"},
        {EnumType::kGuest, "guest"},
    };
};

template <>
struct CppToUserPg<pg_tables::TablesProfileData> {
    static constexpr DBTypeName postgres_name = "tables.profile_data";
};

template <>
struct CppToUserPg<pg_tables::TablesPostsV0> {
    static constexpr DBTypeName postgres_name = "tables.posts_v0";
};

template <>
struct CppToUserPg<pg_tables::TablesUsersV0> {
    static constexpr DBTypeName postgres_name = "tables.users_v0";
};

}  // namespace storages::postgres::io

USERVER_NAMESPACE_END
