components_manager:
    components:
        handler-chaos:
            path: /chaos
            task_processor: main-task-processor
            method: GET,POST,DELETE

        clickhouse-database:
            secdist_alias: clickhouse-database-alias
            initial_pool_size: 1
            max_pool_size: 1
            queue_timeout: 10s
            use_secure_connection: false

        secdist: {}
        default-secdist-provider:
            config: /etc/clickhouse_basic_chaos/secure_data.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        server:
            listener:
                port: 8187
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        tracer:
            service-name: clickhouse-basic-chaos

        dynamic-config:
            fs-cache-path: ''
        dynamic-config-fallbacks:
            fallback-path: /etc/clickhouse_basic_chaos/dynamic_config_fallback.json
        dns-client:
            fs-task-processor: fs-task-processor
    coro_pool:
        initial_size: 500
        max_size: 1000

    task_processors:

        main-task-processor:
            worker_threads: 4
            thread_name: main-worker

        fs-task-processor:
            thread_name: fs-worker
            worker_threads: 4

    default_task_processor: main-task-processor
