components_manager:
    components:
        handler-chaos:
            path: /chaos
            task_processor: main-task-processor
            method: GET,POST,DELETE

        handler-uuids:
            path: /uuids
            task_processor: main-task-processor
            method: GET,POST

        clickhouse-database:
            secdist_alias: clickhouse-database-alias
            initial_pool_size: 1
            max_pool_size: 1
            queue_timeout: 10s
            use_secure_connection: false

        secdist:
            config: /etc/clickhouse_basic_chaos/secure_data.json
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        server:
            listener:
                port: 8187
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        dns-client:
            fs-task-processor: fs-task-processor

    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 4

    default_task_processor: main-task-processor
