/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <client/test/client_impl.hpp>

namespace clients::test {

ClientImpl::ClientImpl(
    const USERVER_NAMESPACE::chaotic::openapi::client::Config& config,
    USERVER_NAMESPACE::clients::http::Client& http_client
)
    : config_(config), http_client_(http_client) {}

testme_post::Response ClientImpl::TestmePost(
    const testme_post::Request& request,
    const USERVER_NAMESPACE::chaotic::openapi::client::CommandControl& command_control
) {
    auto r = http_client_.CreateRequest();
    SerializeRequest(request, r);
    ApplyConfig(r, command_control, config_);

    auto response = r.perform();
    return testme_post::ParseResponse(*response);
}

}  // namespace clients::test
