/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <client/test/component.hpp>

#include <userver/chaotic/openapi/client/config.hpp>
#include <userver/clients/http/component.hpp>
#include <userver/components/component_context.hpp>

namespace clients::test {

Component::Component(
    const USERVER_NAMESPACE::components::ComponentConfig& config,
    const USERVER_NAMESPACE::components::ComponentContext& context
)
    : USERVER_NAMESPACE::components::ComponentBase(config, context),
      client_(
          USERVER_NAMESPACE::chaotic::openapi::client::ParseConfig(config, "http://example.com"),
          context.FindComponent<USERVER_NAMESPACE::components::HttpClient>().GetHttpClient()
      ) {}

Client& Component::GetClient() { return client_; }

}  // namespace clients::test
