/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include "client/test/openapi.hpp"

#include <userver/chaotic/type_bundle_cpp.hpp>

#include "client/test/openapi_parsers.ipp"

namespace clients {
namespace test {
namespace testme_post {}  // namespace testme_post
}  // namespace test
}  // namespace clients
