/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <client/test/requests.hpp>

#include <userver/chaotic/openapi/parameters_write.hpp>
#include <userver/formats/json/value_builder.hpp>

namespace clients::test {

namespace openapi = USERVER_NAMESPACE::chaotic::openapi;

namespace testme_post {

static constexpr openapi::Name knumber = "number";

void SerializeRequest(const Request& request, USERVER_NAMESPACE::clients::http::Request& http_request) {
    openapi::ParameterSinkHttpClient sink(http_request, "/testme");

    WriteParameter<openapi::TrivialParameter<openapi::In::kQuery, knumber, int>>(request.number, sink);

    // http_request.data(ToJsonString(request.body));
    http_request.data(ToString(USERVER_NAMESPACE::formats::json::ValueBuilder(request.body).ExtractValue()));
}

}  // namespace testme_post

}  // namespace clients::test
