/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <client/test/responses.hpp>

namespace clients::test {

namespace testme_post {
Response ParseResponse(USERVER_NAMESPACE::clients::http::Response&) { return Response{}; }
}  // namespace testme_post

}  // namespace clients::test
