/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <dynamic_config/variables/BOOL_FLAG.hpp>

#include <userver/chaotic/primitive.hpp>

namespace dynamic_config {

USERVER_NAMESPACE::dynamic_config::SchemaHash bool_flag::GetSchemaHash() {
    return USERVER_NAMESPACE::dynamic_config::SchemaHash{"7cb541e84f226754a46c21c79f131fa2898354e1242456e6fd1c162bce319553"};
}

namespace {

auto DoParse(const USERVER_NAMESPACE::formats::json::Value& value) {
    return value.As<USERVER_NAMESPACE::chaotic::Primitive<bool>>();
}

}  // anonymous namespace

const USERVER_NAMESPACE::dynamic_config::Key<
    bool
> BOOL_FLAG{
    "BOOL_FLAG",
    DoParse,
    USERVER_NAMESPACE::dynamic_config::DefaultAsJsonString{R"~(
        false
    )~"},
    bool_flag::GetSchemaHash(),
};

}  // namespace dynamic_config
