/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <dynamic_config/variables/CONNECTION_POOL_SETTINGS.hpp>

#include <userver/formats/parse/common_containers.hpp>
#include <userver/formats/serialize/common_containers.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/additional_properties.hpp>
#include <userver/utils/trivial_map.hpp>
#include <userver/formats/parse/common_containers.hpp>
#include <userver/formats/serialize/common_containers.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/formats/parse/common_containers.hpp>
#include <userver/formats/serialize/common_containers.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/io/userver/utils/default_dict.hpp>

#include "dynamic_config/variables/CONNECTION_POOL_SETTINGS.types.hpp"

#include <userver/chaotic/type_bundle_cpp.hpp>

#include "dynamic_config/variables/CONNECTION_POOL_SETTINGS.types_parsers.ipp"

namespace dynamic_config {namespace connection_pool_settings {

PoolSettings FromJsonString(
std::string_view json,
USERVER_NAMESPACE::formats::parse::To<PoolSettings>)
{
return USERVER_NAMESPACE::formats::json::FromString(json).As<PoolSettings>();
}

std::string ToJsonString(const PoolSettings& value) {
return ToString(USERVER_NAMESPACE::formats::json::ValueBuilder(value).ExtractValue());
}

bool operator==(const PoolSettings & lhs,const PoolSettings & rhs) {
return true
&& lhs.min_pool_size == rhs.min_pool_size
&& lhs.max_pool_size == rhs.max_pool_size
;
}

USERVER_NAMESPACE::logging::LogHelper& operator<<(
USERVER_NAMESPACE::logging::LogHelper& lh,
const PoolSettings& value)
{
return lh << ToString(USERVER_NAMESPACE::formats::json::ValueBuilder(value).ExtractValue());
}

PoolSettings Parse(
USERVER_NAMESPACE::formats::json::Value json,
USERVER_NAMESPACE::formats::parse::To<PoolSettings> to)
{
return Parse<USERVER_NAMESPACE::formats::json::Value>(json, to);
}

PoolSettings Parse(
USERVER_NAMESPACE::formats::yaml::Value json,
USERVER_NAMESPACE::formats::parse::To<PoolSettings> to)
{
return Parse<USERVER_NAMESPACE::formats::yaml::Value>(json, to);
}

PoolSettings Parse(
USERVER_NAMESPACE::yaml_config::Value json,
USERVER_NAMESPACE::formats::parse::To<PoolSettings> to)
{
return Parse<USERVER_NAMESPACE::yaml_config::Value>(json, to);
}

USERVER_NAMESPACE::formats::json::Value Serialize(
[[maybe_unused]] const PoolSettings& value,
USERVER_NAMESPACE::formats::serialize::To<USERVER_NAMESPACE::formats::json::Value>)
{
USERVER_NAMESPACE::formats::json::ValueBuilder vb
    = USERVER_NAMESPACE::formats::common::Type::kObject;
vb["min_pool_size"] =
USERVER_NAMESPACE::chaotic::WithType<USERVER_NAMESPACE::chaotic::Primitive<int, USERVER_NAMESPACE::chaotic::Minimum<::dynamic_config::connection_pool_settings::PoolSettings::kMin_Pool_SizeMinimum>>, std::size_t>{
    value.min_pool_size
};
vb["max_pool_size"] =
USERVER_NAMESPACE::chaotic::WithType<USERVER_NAMESPACE::chaotic::Primitive<int, USERVER_NAMESPACE::chaotic::Minimum<::dynamic_config::connection_pool_settings::PoolSettings::kMax_Pool_SizeMinimum>>, std::size_t>{
    value.max_pool_size
};

return vb.ExtractValue();
}

VariableTypeRaw FromJsonString(
std::string_view json,
USERVER_NAMESPACE::formats::parse::To<VariableTypeRaw>)
{
return USERVER_NAMESPACE::formats::json::FromString(json).As<VariableTypeRaw>();
}

std::string ToJsonString(const VariableTypeRaw& value) {
return ToString(USERVER_NAMESPACE::formats::json::ValueBuilder(value).ExtractValue());
}

bool operator==(const VariableTypeRaw & lhs,const VariableTypeRaw & rhs) {
return true
&& lhs.__default__ == rhs.__default__
&& lhs.extra == rhs.extra
;
}

USERVER_NAMESPACE::logging::LogHelper& operator<<(
USERVER_NAMESPACE::logging::LogHelper& lh,
const VariableTypeRaw& value)
{
return lh << ToString(USERVER_NAMESPACE::formats::json::ValueBuilder(value).ExtractValue());
}

VariableTypeRaw Parse(
USERVER_NAMESPACE::formats::json::Value json,
USERVER_NAMESPACE::formats::parse::To<VariableTypeRaw> to)
{
return Parse<USERVER_NAMESPACE::formats::json::Value>(json, to);
}

VariableTypeRaw Parse(
USERVER_NAMESPACE::formats::yaml::Value json,
USERVER_NAMESPACE::formats::parse::To<VariableTypeRaw> to)
{
return Parse<USERVER_NAMESPACE::formats::yaml::Value>(json, to);
}

VariableTypeRaw Parse(
USERVER_NAMESPACE::yaml_config::Value json,
USERVER_NAMESPACE::formats::parse::To<VariableTypeRaw> to)
{
return Parse<USERVER_NAMESPACE::yaml_config::Value>(json, to);
}

USERVER_NAMESPACE::formats::json::Value Serialize(
[[maybe_unused]] const VariableTypeRaw& value,
USERVER_NAMESPACE::formats::serialize::To<USERVER_NAMESPACE::formats::json::Value>)
{
USERVER_NAMESPACE::formats::json::ValueBuilder vb
    ;

    for (const auto&[field_key, field_value]: value.extra) {
        vb.EmplaceNocheck(field_key,
            USERVER_NAMESPACE::chaotic::Primitive<::dynamic_config::connection_pool_settings::PoolSettings>{
                field_value
            }
        );
    }
if (value.__default__) {
vb["__default__"] =
    USERVER_NAMESPACE::chaotic::Primitive<::dynamic_config::connection_pool_settings::PoolSettings>{
        *value.__default__
    };
}

return vb.ExtractValue();
}

}  // namespace connection_pool_settings
}  // namespace dynamic_config

namespace dynamic_config {

USERVER_NAMESPACE::dynamic_config::SchemaHash connection_pool_settings::GetSchemaHash() {
    return USERVER_NAMESPACE::dynamic_config::SchemaHash{"1b31f8984adb341bee5b51b53e44117a8fda141ee6fc89bc4eb910392a3bed37"};
}

namespace {

auto DoParse(const USERVER_NAMESPACE::formats::json::Value& value) {
    return value.As<USERVER_NAMESPACE::chaotic::WithType<USERVER_NAMESPACE::chaotic::Primitive<::dynamic_config::connection_pool_settings::VariableTypeRaw>, USERVER_NAMESPACE::utils::DefaultDict<::dynamic_config::connection_pool_settings::PoolSettings>>>();
}

}  // anonymous namespace

const USERVER_NAMESPACE::dynamic_config::Key<
    USERVER_NAMESPACE::utils::DefaultDict<::dynamic_config::connection_pool_settings::PoolSettings>
> CONNECTION_POOL_SETTINGS{
    "CONNECTION_POOL_SETTINGS",
    DoParse,
    USERVER_NAMESPACE::dynamic_config::DefaultAsJsonString{R"~(
        {}
    )~"},
    connection_pool_settings::GetSchemaHash(),
};

}  // namespace dynamic_config
