/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <dynamic_config/variables/CONNECTION_POOL_SETTINGS.hpp>

#include <userver/formats/parse/common_containers.hpp>
#include <userver/formats/serialize/common_containers.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/additional_properties.hpp>
#include <userver/utils/trivial_map.hpp>
#include <userver/formats/parse/common_containers.hpp>
#include <userver/formats/serialize/common_containers.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/formats/parse/common_containers.hpp>
#include <userver/formats/serialize/common_containers.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/io/userver/utils/default_dict.hpp>

namespace dynamic_config {

namespace {

auto DoParse(const USERVER_NAMESPACE::formats::json::Value& value) {
    return value.As<USERVER_NAMESPACE::chaotic::WithType<USERVER_NAMESPACE::chaotic::Primitive<::dynamic_config::connection_pool_settings::VariableTypeRaw>, USERVER_NAMESPACE::utils::DefaultDict<::dynamic_config::connection_pool_settings::PoolSettings>>>();
}

}  // anonymous namespace

const USERVER_NAMESPACE::dynamic_config::Key<
    USERVER_NAMESPACE::utils::DefaultDict<::dynamic_config::connection_pool_settings::PoolSettings>
> CONNECTION_POOL_SETTINGS{
    "CONNECTION_POOL_SETTINGS",
    DoParse,
    USERVER_NAMESPACE::dynamic_config::DefaultAsJsonString{R"~(
        {}
    )~"},
    "1b31f8984adb341bee5b51b53e44117a8fda141ee6fc89bc4eb910392a3bed37",
};

}  // namespace dynamic_config
