/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */

#include <dynamic_config/variables/FEATURE_FLAGS.hpp>

#include <userver/formats/parse/common_containers.hpp>
#include <userver/formats/serialize/common_containers.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/with_type.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/chaotic/with_type.hpp>

namespace dynamic_config {

namespace {

auto DoParse(const USERVER_NAMESPACE::formats::json::Value& value) {
    return value.As<USERVER_NAMESPACE::chaotic::Primitive<::dynamic_config::feature_flags::VariableTypeRaw>>();
}

}  // anonymous namespace

const USERVER_NAMESPACE::dynamic_config::Key<
    ::dynamic_config::feature_flags::VariableTypeRaw
> FEATURE_FLAGS{
    "FEATURE_FLAGS",
    DoParse,
    USERVER_NAMESPACE::dynamic_config::DefaultAsJsonString{R"~(
        {"enable_new_logic": false, "timeout_ms": 5000}
    )~"},
    "87532654226185e45e1e788e08df6be5e2a748579036dac7c7606f2ac0cd17ef",
};

}  // namespace dynamic_config
