/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <handlers/test/testme/post/requests.hpp>
#include <userver/chaotic/openapi/parameters_read.hpp>
#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>
#include <userver/formats/json/value.hpp>

namespace handlers::test::testme::post {

Request ParseRequest(
    const USERVER_NAMESPACE::server::http::HttpRequest& http_request,
    const USERVER_NAMESPACE::chaotic::openapi::To<Request>& /*tag*/
) {
    namespace openapi = USERVER_NAMESPACE::chaotic::openapi;

    Request r{};

    r.number = openapi::ReadParameter<
        openapi::TrivialParameter<openapi::In::kQuery, knumber, std::string, std::string>>(http_request);

    r.array = openapi::ReadParameter<
        openapi::ArrayParameter<openapi::In::kQuery, karray, ',', std::string, std::string>>(http_request);

    auto json = USERVER_NAMESPACE::formats::json::FromString(http_request.RequestBody());
    r.body = json.As<int>();

    return r;
}

}  // namespace handlers::test::testme::post
