/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <handlers/test/testme/post/responses.hpp>
#include <userver/chaotic/sax_parser.hpp>
#include <userver/formats/json/serialize.hpp>
#include <userver/formats/json/value_builder.hpp>
#include <userver/server/http/http_response.hpp>

namespace handlers::test::testme::post {

namespace {

std::string SerializeSpecificResponse(
    const Response200& r,
    USERVER_NAMESPACE::server::http::HttpRequest& http_request
) {
    http_request.GetHttpResponse().SetStatus(static_cast<USERVER_NAMESPACE::server::http::HttpStatus>(200));

    (void)r;
    return {};
}

}  // namespace

std::string SerializeResponse(const Response& response, USERVER_NAMESPACE::server::http::HttpRequest& http_request) {
    return SerializeSpecificResponse(response, http_request);
}

}  // namespace handlers::test::testme::post
