# yaml
config_vars: config_vars.yaml

components_manager:

    # Preallocate coroutines and tweak the VMEM usage for the benchmark. Not required in production, defaults are fine
    coro_pool:
        initial_size: 5000
        max_size: 1000000
        # In release build 32KB is OK for the existing benchmarks
        #stack_size: 32000

    task_processors:
        main-task-processor:
            # guess-cpu-limit: true
            task-processor-queue: global-task-queue  # `pull-pin-task-queue` could be benifitable, depending on workload
            worker_threads: 4

        fs-task-processor:
            worker_threads: 2

    # Matches default
    event_thread_pool:
        threads: 2

    components:
        server:
            # Production solution:
            #middleware-pipeline-builder: default-server-middleware-pipeline-builder

            # Max performance with close to zero diagnostics
            middleware-pipeline-builder: minimal-server-middleware-pipeline-builder

            listener:
                ports:
                  - port: 8080
                  - port: 8081
                    tls:
                        cert: cert.crt
                        private-key: private_key.key
                task_processor: main-task-processor
                handler-defaults:
                    set_tracing_headers: false
                    max_request_size: 26214400
                    max_headers_size: 65535
            server-name: userver

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: warning
                    overflow_behavior: discard

        dns-client:
            fs-task-processor: fs-task-processor

        http-client:
            load-enabled: $testsuite-enabled
            load-enabled#fallback: false
        http-client-core:
            load-enabled: $testsuite-enabled
            load-enabled#fallback: false
            fs-task-processor: main-task-processor

        dynamic-config:
            updates-enabled: false
            fs-cache-path: ''
            fs-task-processor: fs-task-processor
            defaults:
                USERVER_LOG_REQUEST: false

        testsuite-support:

        tests-control:
            load-enabled: $testsuite-enabled
            load-enabled#fallback: false
            method: POST
            path: /tests/{action}
            task_processor: main-task-processor
            testpoint-timeout: 10s
            testpoint-url: $mockserver/testpoint
            throttling_enabled: false

        noop-tracing-manager:
        tracing-manager-locator:
            component-name: noop-tracing-manager

        fs-cache-static:
            dir: data/static
            update-period: 0
            fs-task-processor: fs-task-processor

        handler-static:
            fs-cache-component: fs-cache-static
            path: /static/*
            method: GET
            task_processor: main-task-processor

        plaintext-handler:
            path: /pipeline
            method: GET
            decompress_request: false
            task_processor: main-task-processor

        baseline11-handler:
            path: /baseline11
            method: GET,POST
            decompress_request: false
            task_processor: main-task-processor

        json-handler:
            path: /json/{count}
            method: GET
            decompress_request: false
            task_processor: main-task-processor
            middlewares:
                pipeline-builder: compression-pipeline-builder

        upload-handler:
            path: /upload
            method: POST
            decompress_request: false
            task_processor: main-task-processor

        async-db-handler:
            path: /async-db
            method: GET
            decompress_request: false
            task_processor: main-task-processor

        baseline2-handler:
            path: /baseline2
            method: GET
            decompress_request: false
            task_processor: main-task-processor

        compression-pipeline-builder:

        compression-middleware: {}

        dataset-provider:
            dataset-path: data/dataset.json

        hello-world-db:
            dbconnection#env: DATABASE_URL
            dbconnection#fallback: 'postgresql://testsuite@localhost:15433/postgres'
            min_pool_size#env: DATABASE_MAX_CONN
            min_pool_size#fallback: 4
            max_pool_size#env: DATABASE_MAX_CONN
            max_pool_size#fallback: 16
            blocking_task_processor: fs-task-processor
            max_queue_size: 200
            connecting_limit: 16
            ignore_unused_query_params: true
            connlimit_mode: manual
            dns_resolver: async
