/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <clients/test/client_impl.hpp>
#include <userver/components/component_base.hpp>
#include <userver/components/component_context.hpp>
#include <userver/yaml_config/merge_schemas.hpp>

namespace clients::test {

ClientImpl::ClientImpl(
    const USERVER_NAMESPACE::chaotic::openapi::client::Config& config,
    USERVER_NAMESPACE::clients::http::Client& http_client
)
    : config_(config),
      http_client_(http_client)
{}

testme::post::Response ClientImpl::TestmePost(
    const testme::post::Request& request,
    const USERVER_NAMESPACE::chaotic::openapi::client::CommandControl& command_control
) {
    auto r = http_client_.CreateRequest();
    r.SetUrlTemplate("/testme");

    if (core_middlewares_) {
        r.SetMiddlewaresList(*core_middlewares_);
    }
    ApplyConfig(r, command_control, config_);
    SerializeRequest(request, config_.base_url, r);

    middleware_manager_.ProcessRequest(r);

    std::shared_ptr<USERVER_NAMESPACE::clients::http::Response> response;
    try {
        response = r.perform();
        middleware_manager_.ProcessResponse(*response);
    } catch (const USERVER_NAMESPACE::clients::http::TimeoutException& e) {
        throw testme::post::TimeoutException();
    }

    return testme::post::ParseResponse(*response);
}

}  // namespace clients::test
