/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <clients/test/exceptions.hpp>
#include <userver/clients/http/error_kind.hpp>

namespace clients::test {

Exception::~Exception() = default;

HttpException::HttpException(USERVER_NAMESPACE::clients::http::ErrorKind error_kind)
    : USERVER_NAMESPACE::chaotic::openapi::client::HttpException(error_kind) {}

ExceptionWithStatusCode::ExceptionWithStatusCode(int status_code)
    : USERVER_NAMESPACE::chaotic::openapi::client::ExceptionWithStatusCode(status_code) {}

TimeoutException::~TimeoutException() = default;

namespace testme::post {

const char* Exception::what() const noexcept { return kHandlerInfo.c_str(); }

HttpException::~HttpException() = default;

TimeoutException::TimeoutException()
    : HttpException(USERVER_NAMESPACE::clients::http::ErrorKind::kTimeout)
{}

TimeoutException::~TimeoutException() = default;

ExceptionWithStatusCode::~ExceptionWithStatusCode() = default;

}  // namespace testme::post

}  // namespace clients::test
