/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <userver/chaotic/type_bundle_cpp.hpp>

#include "clients/test/openapi.hpp"
#include "clients/test/openapi_parsers.ipp"
#include "clients/test/openapi_sax_parsers.hpp"

namespace clients {
namespace test {
namespace testme {
namespace post {}  // namespace post
}  // namespace testme
}  // namespace test
}  // namespace clients
