/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#include <clients/test/responses.hpp>
#include <userver/chaotic/openapi/parameters_read.hpp>
#include <userver/chaotic/sax_parser.hpp>
#include <userver/clients/http/response.hpp>
#include <userver/formats/json/serialize.hpp>
#include <userver/http/common_headers.hpp>
#include <userver/http/content_type.hpp>
#include <userver/logging/log.hpp>

namespace clients::test {

namespace testme::post {
Response ParseResponse(USERVER_NAMESPACE::clients::http::Response& http_response) {
    auto status_code = static_cast<int>(http_response.status_code());
    switch (status_code) {
        case 200: {
            Response200 r{};

            return r;
        }

        default:
            throw ExceptionWithStatusCode(status_code);
    }
}
}  // namespace testme::post

}  // namespace clients::test
