type: object
description: Kafka producer component
additionalProperties: false
properties:
    client_id:
        type: string
        description: |
            Client identifier.
            May be an arbitrary string.
            Optional, but you should set this property on each instance
            because it enables you to more easily correlate requests on the broker
            with the client instance which made it,
            which can be helpful in debugging and troubleshooting scenarios.
        default: userver
    delivery_timeout:
        type: string
        description: time a produced message waits for successful delivery
    queue_buffering_max:
        type: string
        description: delay to wait for messages to be transmitted to broker
    enable_idempotence:
        type: boolean
        description: whether to make producer idempotent
        default: false
    queue_buffering_max_messages:
        type: integer
        description: |
            maximum number of messages allowed on the producer queue. In other
            words, maximum number of simultaneously send requests waiting for delivery
        minimum: 0
        maximum: 2147483647
        default: 100000
    queue_buffering_max_kbytes:
        type: integer
        description: |
            maximum total message size sum allowed on the producer queue. Has
            higher priority than `queue_buffering_max_messages`, i.e. if this limit is
            exceeded no more send requests are accepted regardless to the number of messages
        minimum: 1
        maximum: 2147483647
        default: 1048576
    message_max_bytes:
        type: integer
        description: one message maximum size
        minimum: 1000
        maximum: 1000000000
        default: 1000000
    message_send_max_retries:
        type: integer
        description: maximum number of send request retries until `delivery_timeout`
            reached
        default: 2147483647
    retry_backoff:
        type: string
        description: |
            the backoff time before retrying a producer send request.
            It will be backed off exponentially until number of retries is exhausted
            and bounded by `retry_backoff_max`.
            The backoff must fit in [1ms; 300000ms]
        default: 100ms
    retry_backoff_max:
        type: string
        description: |
            backoff upper bound.
            The backoff must fit in [1ms; 300000ms]
        default: 1000ms
    security_protocol:
        type: string
        description: protocol used to communicate with brokers
        enum:
          - PLAINTEXT
          - SASL_SSL
          - SASL_PLAINTEXT
          - SSL
    sasl_mechanisms:
        type: string
        description: |
            SASL mechanism to use for authentication.
            Must be set if `security_protocol` equals `SASL_SSL`
        default: ''
        enum:
          - PLAIN
          - SCRAM-SHA-512
    ssl_ca_location:
        type: string
        description: |
            file or directory path to CA certificate(s) for verifying the broker's key.
            Must be set if `security_protocol` equals `SASL_SSL` or `SSL`.
            If set to `probe`, CA certificates are probed from the default certificates paths
        default: none

    rd_kafka_custom_options:
        type: object
        description: |
            a map of arbitrary `librdkafka` library configuration options.
            Full list of options is available by link: https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md.
            Note: This options is not guaranteed to be supported in userver-kafka, use it at your own risk
        properties: {}
        additionalProperties:
            type: string
            description: librdkafka option value
        default: {}
    debug_info_log_level:
        type: string
        description: |
            log level for everything debug information
        default: debug
    operation_log_level:
        type: string
        description: |
            log level for infos about ordinary actions
        default: debug
