/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <client/test/client.hpp>

#include <userver/chaotic/openapi/client/config.hpp>
#include <userver/clients/http/client.hpp>

namespace clients::test {

class ClientImpl final : public Client {
public:
    // API

    testme_post::Response TestmePost(
        const testme_post::Request& request,
        const USERVER_NAMESPACE::chaotic::openapi::client::CommandControl& command_control
    ) override;

    // end of API

    static constexpr std::string_view kName = "test";
    static constexpr std::string_view kDefaultBaseUrl = "http://example.com";

    ClientImpl(
        const USERVER_NAMESPACE::chaotic::openapi::client::Config&,
        USERVER_NAMESPACE::clients::http::Client& http_client
    );

private:
    USERVER_NAMESPACE::chaotic::openapi::client::Config config_;
    USERVER_NAMESPACE::clients::http::Client& http_client_;
};

}  // namespace clients::test
