/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include "requests.hpp"
#include "responses.hpp"

#include <userver/chaotic/openapi/client/command_control.hpp>

namespace clients::test {

class Client {
public:
    /// POST /testme
    /// A testing method to call
    /// @throw testme_post::Exception

    virtual testme_post::Response TestmePost(
        const testme_post::Request& request,
        const USERVER_NAMESPACE::chaotic::openapi::client::CommandControl& command_control = {}
    ) = 0;

    virtual ~Client();
};

}  // namespace clients::test
