/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include "client/test/openapi.hpp"

#include <userver/chaotic/primitive.hpp>
#include <userver/chaotic/validators.hpp>

namespace clients {
namespace test {
namespace testme_post {}  // namespace testme_post
}  // namespace test
}  // namespace clients
