/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include "client/test/openapi_fwd.hpp"

#include <cstdint>

#include <userver/chaotic/type_bundle_hpp.hpp>

namespace clients {
namespace test {
namespace testme_post {

using BodyApplicationJson = int;

}  // namespace testme_post
}  // namespace test
}  // namespace clients
