/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <variant>

#include <client/test/exceptions.hpp>
#include <userver/chaotic/openapi/client/exceptions.hpp>

#include <client/test/openapi.hpp>

USERVER_NAMESPACE_BEGIN
namespace clients::http {
class Response;
}
USERVER_NAMESPACE_END

namespace clients::test {

namespace testme_post {

struct Response200 {};

using Response = Response200;

Response ParseResponse(USERVER_NAMESPACE::clients::http::Response& response);
}  // namespace testme_post

}  // namespace clients::test
