/* THIS FILE IS AUTOGENERATED, DON'T EDIT! */
#pragma once

#include <client/test/exceptions.hpp>

USERVER_NAMESPACE_BEGIN
namespace clients::http {
class Response;
}
USERVER_NAMESPACE_END

namespace clients::test {

namespace testme_post {
struct Response {};

Response ParseResponse(USERVER_NAMESPACE::clients::http::Response& response);
}  // namespace testme_post

}  // namespace clients::test
