execute_process(COMMAND dpkg-parsechangelog
    -l ${CMAKE_SOURCE_DIR}/debian/changelog
    --show-field Version
  OUTPUT_VARIABLE DEBVERSION
  OUTPUT_STRIP_TRAILING_WHITESPACE)

if (NOT DEBVERSION)
  set(DEBVERSION 0.0.0)
endif()

string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+"
  PROJECT_VERSION_STRING ${DEBVERSION})

string (REPLACE "." ";" _VERSION_LIST ${PROJECT_VERSION_STRING})
list (GET _VERSION_LIST 0 PROJECT_VERSION_MAJOR)
list (GET _VERSION_LIST 1 PROJECT_VERSION_MINOR)
list (GET _VERSION_LIST 2 PROJECT_VERSION_BUILD)

message ("Project version ${PROJECT_VERSION_STRING}: "
  "major=${PROJECT_VERSION_MAJOR}; "
	"minor=${PROJECT_VERSION_MINOR}; "
  "build=${PROJECT_VERSION_BUILD}")
