option(USERVER_LTO "Use link time optimizations" OFF)

if(NOT USERVER_LTO)
  message(STATUS "LTO: disabled (user request)")
  add_compile_options("-fdata-sections" "-ffunction-sections")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--gc-sections")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--gc-sections")
else()
  message(STATUS "LTO: on")
  include("${USERVER_CMAKE_DIR}/RequireLTO.cmake")
endif()
