# @ingroup download
option(USERVER_DOWNLOAD_PACKAGE_CARES "Download and setup c-ares if no c-ares of matching version was found"
       ${USERVER_DOWNLOAD_PACKAGES}
)

if(USERVER_INSTALL)
    # userver-core links c-ares PUBLIC (a static library must propagate its link
    # dependencies to consumers). A CPM-downloaded c-ares is a real (non-IMPORTED)
    # build target, and it (or its alias c-ares::cares) cannot be added to
    # userver's own install export set, so `install(EXPORT "userver-targets-core"
    # ...)` would fail with "requires target 'c-ares' that is not in any export
    # set". Require a system package instead, matching what the installed
    # userver-core-config.cmake expects via `find_package(c-ares REQUIRED)`.
    #
    # NOTE: this is USERVER_DOWNLOAD_PACKAGE_C_ARES (with underscore between C
    # and ARES), NOT the USERVER_DOWNLOAD_PACKAGE_CARES option declared above.
    # The two are unrelated: USERVER_DOWNLOAD_PACKAGE_CARES only controls the
    # QUIET/REQUIRED branch below, while USERVER_DOWNLOAD_PACKAGE_C_ARES is
    # auto-generated by _userver_module_begin() from Findc-ares.cmake's
    # `CPM_NAME c-ares` (NAME -> upper-case -> "-" replaced with "_") and is
    # what find_package(c-ares) below actually consults internally to decide
    # whether to silently fall back to a CPM download.
    set(USERVER_DOWNLOAD_PACKAGE_C_ARES OFF)
endif()

if(NOT USERVER_FORCE_DOWNLOAD_PACKAGES)
    if(USERVER_DOWNLOAD_PACKAGE_CARES AND NOT USERVER_INSTALL)
        find_package(c-ares 1.16 QUIET)
    else()
        find_package(c-ares 1.16 REQUIRED)
    endif()

    if(c-ares_FOUND)
        return()
    endif()
endif()

if(USERVER_INSTALL)
    message(
        FATAL_ERROR
            "userver-core cannot be built with USERVER_INSTALL=ON: c-ares was not "
            "found as a system package and would be downloaded via CPM, which "
            "cannot be added to a CMake install export set.\n"
            "Install a system c-ares (so find_package(c-ares) succeeds), e.g. "
            "`sudo apt install libc-ares-dev`."
    )
endif()

include(DownloadUsingCPM)
cpmaddpackage(
    NAME c-ares
    VERSION 1.19.0
    URL https://github.com/c-ares/c-ares/archive/cares-1_19_0.tar.gz
    URL_HASH SHA256=948016368481b6c5063b849b6dec2a7fd659eee2174b7f3db22ff1b22055ed2a
    OPTIONS "CARES_INSTALL OFF" "CARES_BUILD_TOOLS OFF" "CARES_SHARED OFF" "CARES_STATIC ON"
)

set(c-ares_FOUND TRUE)
write_package_stub(c-ares)
