#!/bin/sh

. "$TESTSUITE_LIB_UTILS"

if [ "x$REDIS_CONFIG_FILE" = "x" ]; then
    die "REDIS_CONFIG_FILE must be set"
fi

REDIS_SERVER=$(which redis-server)
REDIS_ROLE="standalone"
if [ "x$REDIS_SERVER" = "x" ]; then
    die "No redis-server binary found"
fi

start() {

    echo "Starting redis ($REDIS_ROLE) with config '$REDIS_CONFIG_FILE'..."
    pidfile="$(get_pidfile $REDIS_ROLE)"
    $REDIS_SERVER $REDIS_CONFIG_FILE \
                    --pidfile $pidfile || {
        die "Failed to start redis ($REDIS_ROLE) server"
    }
}

stop() {
    pidfile="$(get_pidfile $REDIS_ROLE)"
    stop_daemon $REDIS_SERVER $pidfile
}

script_main "$@"
