# AUTOGENERATED, DON'T CHANGE THIS FILE!


if (NOT USERVER_CHECK_PACKAGE_VERSIONS)
  unset(Iconv::Iconv_FIND_VERSION)
endif()

if (TARGET Iconv::Iconv)
  if (NOT Iconv::Iconv_FIND_VERSION)
      set(Iconv::Iconv_FOUND ON)
      return()
  endif()

  if (Iconv::Iconv_VERSION)
      if (Iconv::Iconv_FIND_VERSION VERSION_LESS_EQUAL Iconv::Iconv_VERSION)
          set(Iconv::Iconv_FOUND ON)
          return()
      else()
          message(FATAL_ERROR
              "Already using version ${Iconv::Iconv_VERSION} "
              "of Iconv::Iconv when version ${Iconv::Iconv_FIND_VERSION} "
              "was requested."
          )
      endif()
  endif()
endif()

set(FULL_ERROR_MESSAGE "Could not find `Iconv::Iconv` package.\n\tDebian: sudo apt update && sudo apt install libc6-dev\n\tMacOS: brew install libiconv")


include(FindPackageHandleStandardArgs)

find_library(Iconv::Iconv_LIBRARIES_iconv_libiconv
  NAMES iconv libiconv
)
list(APPEND Iconv::Iconv_LIBRARIES ${Iconv::Iconv_LIBRARIES_iconv_libiconv})

find_path(Iconv::Iconv_INCLUDE_DIRS_iconv_h
  NAMES iconv.h
)
list(APPEND Iconv::Iconv_INCLUDE_DIRS ${Iconv::Iconv_INCLUDE_DIRS_iconv_h})



if (Iconv::Iconv_VERSION)
  set(Iconv::Iconv_VERSION ${Iconv::Iconv_VERSION})
endif()

if (Iconv::Iconv_FIND_VERSION AND NOT Iconv::Iconv_VERSION)
  include(DetectVersion)

  if (UNIX AND NOT APPLE)
    deb_version(Iconv::Iconv_VERSION libc6-dev)
  endif()
  if (APPLE)
    brew_version(Iconv::Iconv_VERSION libiconv)
  endif()
endif()

 
find_package_handle_standard_args(
  Iconv::Iconv
    REQUIRED_VARS
      Iconv::Iconv_LIBRARIES
      Iconv::Iconv_INCLUDE_DIRS
      
    FAIL_MESSAGE
      "${FULL_ERROR_MESSAGE}"
)
mark_as_advanced(
  Iconv::Iconv_LIBRARIES
  Iconv::Iconv_INCLUDE_DIRS
  
)

if (NOT Iconv::Iconv_FOUND)
  if (Iconv::Iconv_FIND_REQUIRED)
      message(FATAL_ERROR "${FULL_ERROR_MESSAGE}. Required version is at least ${Iconv::Iconv_FIND_VERSION}")
  endif()

  return()
endif()

if (Iconv::Iconv_FIND_VERSION)
  if (Iconv::Iconv_VERSION VERSION_LESS Iconv::Iconv_FIND_VERSION)
      message(STATUS
          "Version of Iconv::Iconv is '${Iconv::Iconv_VERSION}'. "
          "Required version is at least '${Iconv::Iconv_FIND_VERSION}'. "
          "Ignoring found Iconv::Iconv."
          "Note: Set -DUSERVER_CHECK_PACKAGE_VERSIONS=0 to skip package version checks if the package is fine."
      )
      set(Iconv::Iconv_FOUND OFF)
      return()
  endif()
endif()

 
if (NOT TARGET Iconv::Iconv)
  add_library(Iconv::Iconv INTERFACE IMPORTED GLOBAL)

  target_include_directories(Iconv::Iconv INTERFACE ${Iconv::Iconv_INCLUDE_DIRS})
  target_link_libraries(Iconv::Iconv INTERFACE ${Iconv::Iconv_LIBRARIES})
  
  # Target Iconv::Iconv is created
endif()

if (Iconv::Iconv_VERSION)
  set(Iconv::Iconv_VERSION "${Iconv::Iconv_VERSION}" CACHE STRING "Version of the Iconv::Iconv")
endif()
