#pragma once

/// @file userver/dynamic_config/registered_config_meta.hpp
/// @brief @copybrief dynamic_config::RegisteredConfigMeta

#include <string_view>

#include <userver/dynamic_config/fwd.hpp>

USERVER_NAMESPACE_BEGIN

namespace dynamic_config {

/// @brief Metadata of a single registered dynamic_config::Key.
/// @note Both fields are string_views into the static global registry.
/// The registry is append-only and its storage is never freed, so the views
/// remain valid for the lifetime of the process. However, do not store
/// RegisteredConfigMeta across calls that could modify the registry (i.e.
/// do not capture it before static initialisation completes).
struct RegisteredConfigMeta final {
    std::string_view name;
    /// SHA-256(canonical JSON of schema), lowercase hex, 64 chars.
    /// Empty for keys not generated by chaotic.
    std::string_view schema_hash;
};

}  // namespace dynamic_config

USERVER_NAMESPACE_END
