name: Alpine Linux

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

env:
    UBSAN_OPTIONS: print_stacktrace=1
    ASAN_OPTIONS: detect_odr_violation=2
    CXX: clang++-18

jobs:
    posix:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - cmake-flags: >-
                    os: ubuntu-24.04
                    info: Alpine linux

        name: '${{matrix.os}}: ${{matrix.info}}'
        runs-on: ${{matrix.os}}

        steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Setup latest Alpine Linux
            uses: jirutka/setup-alpine@v1

          - name: Run script inside Alpine chroot as root
            shell: alpine.sh --root {0}
            run: |
              cat /etc/alpine-release
              apt add $(cat scripts/docs/en/deps/alpine.md)

          - name: Run cmake
            shell: alpine.sh --root {0}
            run: |
                mkdir build_debug
                cd build_debug
                cmake \
                    -DCMAKE_BUILD_TYPE=Debug \
                    -DUSERVER_NO_WERROR=OFF \
                    -DUSERVER_FEATURE_JEMALLOC=OFF \
                    -DUSERVER_FEATURE_ROCKS=OFF \
                    -DUSERVER_FEATURE_MYSQL=OFF \
                    ..

          - name: Compile
            shell: alpine.sh --root {0}
            run: |
                pwd
                cd build_debug
                make -j$(nproc)
