name: Conan

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

env:
    UBSAN_OPTIONS: print_stacktrace=1

jobs:
    build:
        runs-on: ubuntu-${{ matrix.ubuntu_version }}
        name: Ubuntu-${{ matrix.ubuntu_version }}
        strategy:
            fail-fast: false
            matrix:
                ubuntu_version: [22.04]

        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - name: Reuse ccache directory
            uses: actions/cache@v2
            with:
                path: ~/.ccache
                key: '${{matrix.os}} ${{matrix.info}} ccache-dir ${{github.ref}} run-${{github.run_number}}'
                restore-keys: |
                    ${{matrix.os}} ${{matrix.info}} ccache-dir ${{github.ref}} run-'
                    ${{matrix.os}} ${{matrix.info}} ccache-

          - name: Install packages
            run: |
                sudo apt-get install -y gcc g++ cmake wget git python3 python3-pip ccache virtualenv
                pip install jinja2 voluptuous pyyaml "conan>=1.51.0,<2.0.0" protobuf
                conan profile new --detect default && conan profile update settings.compiler.libcxx=libstdc++11 default

          - name: Setup ccache
            run: |
                ccache -M 2.0GB
                ccache -s

          - name: Run conan
            run: |
                conan create . --build=missing -pr:b=default -tf conan/test_package/
