name: Docker

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          
          - name: Build and tests
            run: NPROCS=$(nproc) docker-compose run --rm userver-tests
