name: Docker build

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: Reuse ccache directory
            uses: actions/cache@v2
            with:
                path: ~/.ccache/
                key: 'ccache-dir-${{github.ref}}_run-${{github.run_number}}'
                restore-keys: |
                    ccache-dir-${{github.ref}}_run-
                    ccache-

          - name: Create network
            run: docker network create --subnet=172.16.2.0/24 --gateway=172.16.2.1 --ipv6 --subnet=2001::/16 dockerbridge

          - name: Setup ccache
            run: docker-compose run --rm userver-debian bash -c 'ccache -M 2.0GB && ccache -s'

          - name: Cmake
            run: docker-compose run --rm userver-debian cmake -B./build -S./

          - name: Build
            run: docker-compose run --rm userver-debian bash -c 'cd /userver/build && make -j $(nproc)'

          - name: Run tests
            run: docker-compose run --rm userver-debian bash -c 'cd /userver/build && ctest -V'
