name: Docker build

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          
          - name: Cmake
            run: docker-compose run --rm userver-debian cmake -B./build -S./

          - name: Build
            run: docker-compose run --rm userver-debian bash -c 'cd /userver/build && make -j $(nproc)'

          - name: Run tests
            run: docker-compose run --rm userver-debian bash -c 'cd /userver/build && ctest -V'
